### ISSUE TITLE
specifying multiple creators

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/SSSOM#62]
In the only examples there is a single creator

can a list be provided using yaml list syntax? the linkml doesn't declare this as multivalued.

**Comment by hrshdhgd** [comment]
Example: [tsv file](https://github.com/tdwg/gbwg/blob/main/dwc-mixs/mapping/DwC-MIxS_mappingSemantic.tsv) to `validate`. Error:

--- Logging error ---
Traceback (most recent call last):
  File "/Users/HHegde/Desktop/gitRepo/mapping-commons/sssom-py/sssom/io.py", line 90, in validate_file
    from_tsv(file_path=input_path)
  File "/Users/HHegde/Desktop/gitRepo/mapping-commons/sssom-py/sssom/parsers.py", line 34, in from_tsv
    meta = _read_metadata_from_table(file_path)
  File "/Users/HHegde/Desktop/gitRepo/mapping-commons/sssom-py/sssom/parsers.py", line 421, in _read_metadata_from_table
    meta = yaml.safe_load(yamlstr)
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/anaconda3/envs/sssom--py38/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    This mapping was created followi ... 
    ^
expected <block end>, but found ','
  in "<unicode string>", line 4, column 52:
     ... //orcid.org/0000-0003-1336-5554", "https://orcid.org/0000-0001-9 ... 

this was due to this line:

#creator_id: "https://orcid.org/0000-0003-1336-5554", "https://orcid.org/0000-0001-9625-1899", "https://orcid.org/0000-0002-6601-2165", "https://orcid.org/0000-0003-1144-0290", "https://orcid.org/0000-0002-8083-6048", "https://orcid.org/0000-0003-3770-3714", "https://orcid.org/0000-0002-4366-3088", "https://orcid.org/0000-0002-4236-0384", "https://orcid.org/0000-0001-8815-0078", "https://orcid.org/0000-0002-2996-719X", "https://orcid.org/0000-0001-9401-8460", "https://orcid.org/0000-0003-1691-239X", "https://orcid.org/0000-0001-6215-3617", "https://orcid.org/0000-0002-3237-4547", "https://orcid.org/0000-0001-7087-2646"

When I replaced the `", "` between the ORCIDs by a whitespace, it fixed the issue and the file seemed valid.

There is a need to make the error more informative. The `validate` code needs to address this.

**Comment by wdduncan** [comment]
Are formalizing how creators are specified? If so, can we do something like this:
```
#creator:
#  - William D. Duncan [https://orcid.org/0000-0001-9625-1899]
```
or
```
#creator:
#  https://orcid.org/0000-0001-9625-1899: William D. Duncan
```
issue also mentioned in https://github.com/tdwg/gbwg/issues/69

**Comment by matentzn** [comment]
I would kind of prefer this was solved at tool level rather than in the metadata itself.. It will be really hard to provide validation if we allow complex patterns like this - think that the same metadata item also goes into columns (its not required to have creator up on mapping set level).

**Comment by cthoyt** [comment]
I'm pretty sure this is already solved - creator, author, and reviewer can all be specified as with pipe-delimited lists
